name: "Sphinx Build Test"
on:
- pull_request

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install QExPy and dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt --upgrade
        pip install -r requirements-dev.txt --upgrade
        pip install .
    - uses: Queens-Physics/sphinx-action@master
      with:
        docs-folder: "docs/"
