name: "Sphinx Build Test"
on:
- pull_request

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Queens-Physics/sphinx-action@master
      with:
        docs-folder: "docs/"
